#!/usr/bin/env python3
"""Regenerate the source directory section of QA_REPORT.md from resources.json.

The directory lists, for every entry, each populated sourced field with the
exact URL it is cited to, the geocode provenance, lastVerified, and which
ground-truth QA rounds (qa_history.json) have fetched-and-checked the entry.
Runs on stdlib only. Idempotent: rewrites only the block between the
DIRECTORY markers, creating it at the end of the file if absent.
"""
import json
import sys
from pathlib import Path

HERE = Path(__file__).parent
BEGIN = "<!-- SOURCE-DIRECTORY:BEGIN (generated by qa_directory.py — do not edit by hand) -->"
END = "<!-- SOURCE-DIRECTORY:END -->"


def main() -> int:
    data = json.loads((HERE / "resources.json").read_text())
    history = json.loads((HERE / "qa_history.json").read_text())

    known = {e["id"] for e in data}
    coverage: dict[str, list[str]] = {}
    for rnd in history["rounds"]:
        for i in rnd["ids"]:
            if i not in known:
                print(f"qa_directory.py: WARNING unknown id in qa_history.json: {i}")
            coverage.setdefault(i, []).append(rnd["label"])

    lines = [BEGIN, "", "## Source directory (auto-generated)", ""]
    total = len(data)
    sampled = sum(1 for e in data if e["id"] in coverage)
    lines += [
        f"All {total} entries with every populated value's exact source. "
        f"{sampled} of {total} entries ({sampled * 100 // total}%) have additionally had "
        "their sourced fields fetched and checked against the cited pages by the "
        "report-only QA agent (rounds in the right column; details in the session "
        "logs above). Every entry, sampled or not, passes verify.py's structural "
        "wall on every build.",
        "",
        "| Entry | Field | Cited source | Last verified | QA rounds |",
        "|---|---|---|---|---|",
    ]

    for e in sorted(data, key=lambda x: x["id"]):
        rounds = "; ".join(coverage.get(e["id"], [])) or "—"
        rows = []
        for field in ("phone", "address", "hours", "website"):
            v = e["contact"][field]
            if v["value"]:
                rows.append((field, v["source"]))
        if e["geo"]["lat"] is not None:
            rows.append(("geo", e["geo"]["source"]))
        if not rows:
            rows.append(("(no sourced contact values)", ""))
        first = True
        for field, src in rows:
            name_cell = f"**{e['name']}** (`{e['id']}`)" if first else ""
            date_cell = e["lastVerified"] if first else ""
            rounds_cell = rounds if first else ""
            src_cell = f"[{src}]({src})" if src else ""
            lines.append(f"| {name_cell} | {field} | {src_cell} | {date_cell} | {rounds_cell} |")
            first = False

    lines += ["", END]
    block = "\n".join(lines)

    report_path = HERE / "QA_REPORT.md"
    text = report_path.read_text()
    if BEGIN in text and END in text:
        pre = text.split(BEGIN)[0]
        post = text.split(END)[1]
        text = pre + block + post
    else:
        text = text.rstrip() + "\n\n---\n\n" + block + "\n"
    report_path.write_text(text)
    print(f"qa_directory.py: OK — {total} entries, {sampled} QA-sampled, directory regenerated in QA_REPORT.md")
    return 0


if __name__ == "__main__":
    sys.exit(main())
